language: node_js
node_js:
- '10'
sudo: true
install:
- npm install
- gem install sass
- npm install --save node-sass grunt-sass
script:
- npm run compile
- zip -r "disqus-conditional-load-M-$TRAVIS_TAG.zip" -@ < filelist.txt
deploy:
  provider: releases
  file: disqus-conditional-load-M-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: fHqAu0+cTEO9cCcvzYO9gjvj0voec0L/9B5f4SCRD6CRuBpkjiMQDC5OfaOVX7/DTTkQDiFtkB+27p2XMjAJHkGp2Ax3dnrVtU9vlKWno/bqvjvU0rI+0Hpjp/HI6ndH1QdEY1R79LqH4l2pbAJcu9ztVA3GF4BW0LDSKLF4tJz6pXl0R6cl6nTl1UoqxfyxD7JQLldh/PJ6wN57PBZN8pcWMp/788SIaLPCcjinU8A20RSIJPbm8ORBgSAGBdOO/fwFPL90Icf1x2gE958tmTHb0QvRr/Wf5+3tHDipjrEjqgVpmK8LWzQhPuzozSO0E+EJUVdRr8YOdMsIT3Ayx0tOwkZmkuwYeXdR/2NowQsvrZqZS8O633TURPp1PCjNLAk+siLjmUUpEM3Mhvo3VUddRJscRnDykC7/fzA90/dtViNnHgy9sKoGHOwP8+9HwR4reS7tLRIQ3Z4CUZxlAc0oot3ubaFQiw0InhkdTu0uvCQQdYVUGLv0e2+qy3i6LF4SBUW168FGTk4xTnyUyCabESyn8aP5oc4trAGdrQgeUYfoxnuFKMj3wE4wqrXJvWXeixH1dt/qsLH0eEoLRv42O7Q+uMF+m64I6Pt3YgRLJVohLrFeItY3Opei/ts3yIxK3BN3j6l67wIWQ9EODntYhqOILhi5UWb6ewWf2HU=
